In [37]:
import numpy as np
import pandas as pd

rnames = ['user_id', 'movie_id', 'rating', 'timestamp'] 
ratings = pd.read_table('../data/ml-1m/ratings.dat', sep='::',engine='python', header=None, names=rnames)

In [41]:
ratings

user_id  movie_id  rating  timestamp
0              1      1193       5  978300760
1              1       661       3  978302109
2              1       914       3  978301968
3              1      3408       4  978300275
4              1      2355       5  978824291
5              1      1197       3  978302268
6              1      1287       5  978302039
7              1      2804       5  978300719
8              1       594       4  978302268
9              1       919       4  978301368
10             1       595       5  978824268
11             1       938       4  978301752
12             1      2398       4  978302281
13             1      2918       4  978302124
14             1      1035       5  978301753
15             1      2791       4  978302188
16             1      2687       3  978824268
17             1      2018       4  978301777
18             1      3105       5  978301713
19             1      2797       4  978302039
20             1      2321       3  978302205
21             1       720       3  978300760
22             1      1270       5  978300055
23             1       527       5  978824195
24             1      2340       3  978300103
25             1        48       5  978824351
26             1      1097       4  978301953
27             1      1721       4  978300055
28             1      1545       4  978824139
29             1       745       3  978824268
...          ...       ...     ...        ...
1000179     6040      2762       4  956704584
1000180     6040      1036       3  956715455
1000181     6040       508       4  956704972
1000182     6040      1041       4  957717678
1000183     6040      3735       4  960971654
1000184     6040      2791       4  956715569
1000185     6040      2794       1  956716438
1000186     6040       527       5  956704219
1000187     6040      2003       1  956716294
1000188     6040       535       4  964828734
1000189     6040      2010       5  957716795
1000190     6040      2011       4  956716113
1000191     6040      3751       4  964828782
1000192     6040      2019       5  956703977
1000193     6040       541       4  956715288
1000194     6040      1077       5  964828799
1000195     6040      1079       2  956715648
1000196     6040       549       4  956704746
1000197     6040      2020       3  956715288
1000198     6040      2021       3  956716374
1000199     6040      2022       5  956716207
1000200     6040      2028       5  956704519
1000201     6040      1080       4  957717322
1000202     6040      1089       4  956704996
1000203     6040      1090       3  956715518
1000204     6040      1091       1  956716541
1000205     6040      1094       5  956704887
1000206     6040       562       5  956704746
1000207     6040      1096       4  956715648
1000208     6040      1097       4  956715569

[1000209 rows x 4 columns]

In [34]:
Ys = np.mat(ratings)
Ys

matrix([[        1,      1193,         5, 978300760],
        [        1,       661,         3, 978302109],
        [        1,       914,         3, 978301968],
        ..., 
        [     6040,       562,         5, 956704746],
        [     6040,      1096,         4, 956715648],
        [     6040,      1097,         4, 956715569]])

In [125]:
Nr = 6040 # Number of users
Nc = 3952 # Number of movies
Nk = 2

Ysize = Ys.shape[0]

A = np.mat(np.random.rand(Nr, Nk))
B = np.mat(np.random.rand(Nk, Nc))

EPOCH = 100
Eta = 0.1
eta = Eta
sample = 50000 # 50000 random rating will be chosen and error will be calculated only for those

#Obtain M matrix and Y matrix
M = np.mat(np.zeros((Nr, Nc)))
Y = np.mat(np.zeros((Nr, Nc)))

for i in range(Ysize):
    user = Ys[i,0]
    movie = Ys[i,1]
    M[user-1, movie-1] = 1;
    Y[user-1, movie-1] = Ys[i, 2]
 
Y

matrix([[ 5.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 3.,  0.,  0., ...,  0.,  0.,  0.]])

In [126]:
for i in range(EPOCH):
    E = np.array(M)*np.array(Y - A*B)
    Err = np.sum(E*E)/np.sum(np.array(M))
    if i%10==0:
        print(Err)
    np.random.shuffle(Ys)
    
    for k in range(sample):
        #k = np.random.randint(0, Ysize)
        
        u = Ys[k,0] - 1
        m = Ys[k,1] - 1
        
        err = Ys[k,2] - A[u,:]*B[:,m]
        
        temp_A = A[u,:] + eta*err[0,0]*B[:,m].T
        B[:,m]   = B[:,m] + eta*err[0,0]*A[u,:].T
        A[u,:]   = temp_A
    
    eta = Eta*1./(i+1)

Yr = A*B
Yr

10.8316889325
0.869140229994
0.842302863522
0.834401840883
0.829917998076
0.827403225737
0.82559378991
0.824215830154
0.823266332522
0.822331605801


matrix([[ 4.21015701,  3.2469281 ,  3.18366263, ...,  3.81315771,
          4.05331565,  4.11818247],
        [ 3.98883413,  3.06847505,  3.01465502, ...,  3.63083144,
          3.85507223,  3.94309259],
        [ 4.25654225,  3.31208763,  3.22496815, ...,  3.78657643,
          4.04183864,  4.00690285],
        ..., 
        [ 3.39727066,  2.62216591,  2.56942419, ...,  3.07191298,
          3.2666118 ,  3.31161254],
        [ 4.02229178,  3.15923312,  3.053725  , ...,  3.50951972,
          3.76320644,  3.62956273],
        [ 3.71192063,  2.88811952,  2.81229569, ...,  3.30252729,
          3.52504884,  3.49522885]])

In [134]:

result = np.zeros([20, 10])

Yp = A*B # This is a dummy matrix to be used while searching the max rated movies

# Find out the indeces of the maximum values in each row (corresponds to users)
# These indeces will be the max rated movies of this user
# In the assignment, we were asked to find out the 10 max rated movies of the first 20 users

for i in range(20):
    for j in range(10):
        idx = np.argmax(Yp[i, :])
        result[i, j] = idx
        Yp[i, idx] = 0 # reset to invalid rating to prevent this index to be found in further search


for i in range(20):
    u= str(i+1)
    print("User #" + u + "'s highest rating movies are:")
    for k in range(10):
        m = str(result[i, k])
        rate = round(Yr[i-1, result[i, k]], 3) # to get rid of unnecessary decimals
        rate = str(rate)
        print("\tMovie #" + m + " with rating " + rate)

User #1's highest rating movies are:
	Movie #2018.0 with rating 4.212
	Movie #2904.0 with rating 4.198
	Movie #49.0 with rating 4.131
	Movie #1177.0 with rating 4.11
	Movie #1211.0 with rating 4.071
	Movie #3434.0 with rating 4.073
	Movie #857.0 with rating 4.117
	Movie #921.0 with rating 4.121
	Movie #749.0 with rating 4.066
	Movie #1147.0 with rating 4.084
User #2's highest rating movies are:
	Movie #2018.0 with rating 4.858
	Movie #2904.0 with rating 4.79
	Movie #49.0 with rating 4.755
	Movie #1211.0 with rating 4.739
	Movie #3434.0 with rating 4.736
	Movie #1177.0 with rating 4.739
	Movie #857.0 with rating 4.736
	Movie #921.0 with rating 4.733
	Movie #749.0 with rating 4.704
	Movie #1147.0 with rating 4.702
User #3's highest rating movies are:
	Movie #2018.0 with rating 4.624
	Movie #2904.0 with rating 4.545
	Movie #49.0 with rating 4.524
	Movie #921.0 with rating 4.501
	Movie #857.0 with rating 4.504
	Movie #903.0 with rating 4.424
	Movie #1177.0 with rating 4.511
	Movie #317.0 w