#STOCHASTIC GRADIENT DESCENT#

In [15]:
import numpy as np
import pandas as pd
import time


rnames = ['user_id', 'movie_id', 'rating', 'timestamp'] 
ratings = pd.read_table('../data/ml-1m/ratings.dat', sep='::',engine='python', header=None, names=rnames)

In [16]:
ratings

user_id  movie_id  rating  timestamp
0              1      1193       5  978300760
1              1       661       3  978302109
2              1       914       3  978301968
3              1      3408       4  978300275
4              1      2355       5  978824291
5              1      1197       3  978302268
6              1      1287       5  978302039
7              1      2804       5  978300719
8              1       594       4  978302268
9              1       919       4  978301368
10             1       595       5  978824268
11             1       938       4  978301752
12             1      2398       4  978302281
13             1      2918       4  978302124
14             1      1035       5  978301753
15             1      2791       4  978302188
16             1      2687       3  978824268
17             1      2018       4  978301777
18             1      3105       5  978301713
19             1      2797       4  978302039
20             1      2321       3  978302205
21             1       720       3  978300760
22             1      1270       5  978300055
23             1       527       5  978824195
24             1      2340       3  978300103
25             1        48       5  978824351
26             1      1097       4  978301953
27             1      1721       4  978300055
28             1      1545       4  978824139
29             1       745       3  978824268
...          ...       ...     ...        ...
1000179     6040      2762       4  956704584
1000180     6040      1036       3  956715455
1000181     6040       508       4  956704972
1000182     6040      1041       4  957717678
1000183     6040      3735       4  960971654
1000184     6040      2791       4  956715569
1000185     6040      2794       1  956716438
1000186     6040       527       5  956704219
1000187     6040      2003       1  956716294
1000188     6040       535       4  964828734
1000189     6040      2010       5  957716795
1000190     6040      2011       4  956716113
1000191     6040      3751       4  964828782
1000192     6040      2019       5  956703977
1000193     6040       541       4  956715288
1000194     6040      1077       5  964828799
1000195     6040      1079       2  956715648
1000196     6040       549       4  956704746
1000197     6040      2020       3  956715288
1000198     6040      2021       3  956716374
1000199     6040      2022       5  956716207
1000200     6040      2028       5  956704519
1000201     6040      1080       4  957717322
1000202     6040      1089       4  956704996
1000203     6040      1090       3  956715518
1000204     6040      1091       1  956716541
1000205     6040      1094       5  956704887
1000206     6040       562       5  956704746
1000207     6040      1096       4  956715648
1000208     6040      1097       4  956715569

[1000209 rows x 4 columns]

In [17]:
Ys = np.mat(ratings)
Ys

matrix([[        1,      1193,         5, 978300760],
        [        1,       661,         3, 978302109],
        [        1,       914,         3, 978301968],
        ..., 
        [     6040,       562,         5, 956704746],
        [     6040,      1096,         4, 956715648],
        [     6040,      1097,         4, 956715569]])

In [20]:
Nr = 6040 # Number of users
Nc = 3952 # Number of movies
Nk = 2

Ysize = Ys.shape[0]

A = np.mat(np.random.rand(Nr, Nk))
B = np.mat(np.random.rand(Nk, Nc))

EPOCH = 10
Eta = 0.1
eta = Eta
sample = 50000 # 50000 random rating will be chosen and error will be calculated only for those

#Obtain M matrix and Y matrix
M = np.mat(np.zeros((Nr, Nc)))
Y = np.mat(np.zeros((Nr, Nc)))

for i in range(Ysize):
    user = Ys[i,0]
    movie = Ys[i,1]
    M[user-1, movie-1] = 1;
    Y[user-1, movie-1] = Ys[i, 2]
 
Y

matrix([[ 5.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 3.,  0.,  0., ...,  0.,  0.,  0.]])

In [24]:

start_time = time.clock()

np.random.shuffle(Ys)

for i in range(EPOCH):
    if i==(EPOCH-1):
        E = np.array(M)*np.array(Y - A*B)
        Err = np.sum(E*E)/np.sum(np.array(M))
        print(Err)
    
    for k in range(Ysize):
        #k = np.random.randint(0, Ysize)
        
        u = Ys[k,0] - 1
        m = Ys[k,1] - 1
        
        err = Ys[k,2] - A[u,:]*B[:,m]
        
        temp_A = A[u,:] + eta*err[0,0]*B[:,m].T
        B[:,m]   = B[:,m] + eta*err[0,0]*A[u,:].T
        A[u,:]   = temp_A
    
    eta = Eta*1./(i+1)

time_sgd = time.clock() - start_time
print time_sgd, "seconds"

Yr = A*B
Yr

624.58 seconds


matrix([[ 4.27807442,  3.86247738,  3.64432584, ...,  3.36693038,
          3.46606086,  3.86124788],
        [ 4.32623421,  3.75233663,  3.44881209, ...,  3.49059826,
          3.68499156,  3.89023856],
        [ 4.19620525,  3.8759179 ,  3.70909159, ...,  3.25372776,
          3.29742499,  3.79558762],
        ..., 
        [ 3.84723143,  3.2386321 ,  2.91568694, ...,  3.15896581,
          3.39204439,  3.45025129],
        [ 4.05963562,  3.35688727,  2.9834315 , ...,  3.36717454,
          3.65022829,  3.6350325 ],
        [ 3.35420426,  2.11055705,  1.44413535, ...,  3.15222184,
          3.79241635,  2.94090337]])

In [25]:

result = np.zeros([20, 10])

Yp = A*B # This is a dummy matrix to be used while searching the max rated movies

# Find out the indeces of the maximum values in each row (corresponds to users)
# These indeces will be the max rated movies of this user
# In the assignment, we were asked to find out the 10 max rated movies of the first 20 users

for i in range(20):
    for j in range(10):
        idx = np.argmax(Yp[i, :])
        result[i, j] = idx
        Yp[i, idx] = 0 # reset to invalid rating to prevent this index to be found in further search


for i in range(20):
    u= str(i+1)
    print("User #" + u + "'s highest rating movies are:")
    for k in range(10):
        m = str(result[i, k])
        rate = round(Yr[i-1, result[i, k]], 3) # to get rid of unnecessary decimals
        rate = str(rate)
        print("\tMovie #" + m + " with rating " + rate)

User #1's highest rating movies are:
	Movie #3381.0 with rating 4.608
	Movie #3171.0 with rating 2.999
	Movie #571.0 with rating 3.141
	Movie #556.0 with rating 5.241
	Movie #438.0 with rating 2.604
	Movie #2196.0 with rating 2.303
	Movie #988.0 with rating 3.957
	Movie #786.0 with rating 4.067
	Movie #3606.0 with rating 3.744
	Movie #36.0 with rating 1.349
User #2's highest rating movies are:
	Movie #3381.0 with rating 6.319
	Movie #556.0 with rating 5.375
	Movie #3171.0 with rating 5.515
	Movie #571.0 with rating 5.463
	Movie #988.0 with rating 5.115
	Movie #438.0 with rating 5.269
	Movie #786.0 with rating 4.938
	Movie #2196.0 with rating 5.172
	Movie #3232.0 with rating 4.77
	Movie #3606.0 with rating 4.826
User #3's highest rating movies are:
	Movie #3381.0 with rating 6.332
	Movie #3171.0 with rating 5.355
	Movie #571.0 with rating 5.333
	Movie #438.0 with rating 5.073
	Movie #2196.0 with rating 4.937
	Movie #556.0 with rating 5.607
	Movie #988.0 with rating 5.164
	Movie #36.0 wi

#GRADIENT DESCENT#    ----- INCOMPLETE AFTER THIS POINT ON...

In [61]:
A = np.mat(np.random.rand(Nr, Nk))
B = np.mat(np.random.rand(Nk, Nc))

temp_A = np.mat(np.random.rand(Nr, Nk))
temp_B = np.mat(np.random.rand(Nk, Nc))

err = np.mat(np.zeros((Nr, Nc)))
errT = np.mat(np.zeros((Nc, Nr)))

EPOCH = 20
eta=0.001

start_time = time.clock()

for i in range(EPOCH):

    errT = np.array(M.T)*np.array(Y.T - B.T*A.T)
    Err = np.sum(errT*errT)/np.sum(np.array(M))
    #if i==(EPOCH-1): 
    print(Err)

    gB = -errT*A
    B = B - eta*gB.T
    
    
for i in range(EPOCH):

    err = np.array(M)*np.array(Y - A*B)
    Err = np.sum(err*err)/np.sum(np.array(M))
    print(Err)
    
    gA = -err*B.T
    A = A - eta*gA

    
time_gd = time.clock() - start_time
print time_gd, "seconds"

Yr = A*B
Yr

10.8759790031
5.82197177601
4.56714775477
4.01011699164
3.70169411514
3.50896305384
3.37899214646
3.28661298853
3.21837412575
3.16646779476
3.12607470508
3.09407438453
3.06836687959
3.04749315148
3.03041178206
3.01636211574
3.00477741474
2.99522807727
2.98738352795
2.980986042
2.97583239212
97.4167893934
17703.369673
5517220.10255
2299283334.41
1.12190785744e+12
5.96394412837e+14
3.3301519319e+17
1.91755835242e+20
1.12786496613e+23
6.74299693261e+25
4.088081818e+28
2.51153919094e+31
1.56416193257e+34
9.88718197991e+36
6.35485857209e+39
4.16237739312e+42
2.78471469524e+45
1.90684821053e+48
1.33835908875e+51
89.99 seconds


matrix([[  4.47706737e+00,   3.42987558e+00,   3.24159331e+00, ...,
           2.28162249e+00,   1.85465588e+00,   3.94568051e+00],
        [  5.50666232e+03,   4.21835035e+03,   3.98732162e+03, ...,
           2.80602421e+03,   2.28151274e+03,   4.85321921e+03],
        [  4.32207134e+00,   3.41387696e+00,   3.04056004e+00, ...,
           2.30825975e+00,   1.67263505e+00,   3.75807801e+00],
        ..., 
        [  4.01542224e+00,   3.05147513e+00,   2.92872211e+00, ...,
           2.02092804e+00,   1.69177867e+00,   3.55110701e+00],
        [ -6.63714946e+04,  -5.08838103e+04,  -4.80241589e+04, ...,
          -3.38622519e+04,  -2.74527722e+04,  -5.84755917e+04],
        [ -9.16459802e+14,  -7.02141978e+14,  -6.63519702e+14, ...,
          -4.67094731e+14,  -3.79600114e+14,  -8.07662931e+14]])